/*
CREATE DATABASE 

DROP TABLE 
TRUNCATE 

SELECT * FROM RAW_PetData;
SELECT * FROM PKPetData;
*/

USE quanly_Lab3
GO

CREATE TABLE tblPET_TYPE (
    PetTypeID INT IDENTITY(1,1) PRIMARY KEY,
    PetTypeName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblCOUNTRY (
    CountryID INT IDENTITY(1,1) PRIMARY KEY,
    CountryName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblTEMPERAMENT (
    TempID INT IDENTITY(1,1) PRIMARY KEY,
    TempName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblGENDER (
    GenderID INT IDENTITY(1,1) PRIMARY KEY,
    GenderName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblPET (
    PetID INT IDENTITY(1,1) PRIMARY KEY,
    PetName VARCHAR(50) NOT NULL,
    Cost NUMERIC(8, 2) NOT NULL,
    Price NUMERIC(8, 2) NOT NULL,
    DOB DATE NULL,
    PetTypeID INT FOREIGN KEY REFERENCES tblPET_TYPE(PetTypeID) NOT NULL,
    TempID INT FOREIGN KEY REFERENCES tblTEMPERAMENT(TempID) NOT NULL,
    CountryID INT FOREIGN KEY REFERENCES tblCOUNTRY(CountryID) NOT NULL,
    GenderID INT FOREIGN KEY REFERENCES tblGENDER(GenderID) NOT NULL
);
GO

CREATE TABLE tblHOBBY (
    HobbyID INT IDENTITY(1,1) PRIMARY KEY,
    HobbyName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE tblPET_HOBBY (
    PetHobbyID INT IDENTITY(1,1) PRIMARY KEY,
    Points NUMERIC(8, 2) NOT NULL,
    PetID INT FOREIGN KEY REFERENCES tblPET(PetID) NOT NULL,
    HobbyID INT FOREIGN KEY REFERENCES tblHOBBY(HobbyID) NOT NULL
);
GO

-- Create primary key table
CREATE TABLE PKPetData (
    petPK INT IDENTITY(1,1) PRIMARY KEY,
    PETNAME VARCHAR(250),
    PET_TYPE VARCHAR(250),
    TEMPERAMENT VARCHAR(250),
    COUNTRY VARCHAR(250),
    DATE_BIRTH DATE,
    GENDER VARCHAR(250),
    HOBBY1 VARCHAR(250),
    HOBBY2 VARCHAR(250),
    HOBBY3 VARCHAR(250),
    HOBBY4 VARCHAR(250),
    COST NUMERIC(8,2)
);
GO

-- Clean raw data (scrub null values)
-- Hobby, cost not required?
INSERT INTO PKPetData
    SELECT PETNAME, PET_TYPE, TEMPERAMENT, COUNTRY, DATE_BIRTH, GENDER, HOBBY1, HOBBY2, HOBBY3, HOBBY4, COST
    FROM RAW_PetData
    WHERE
    PETNAME IS NOT NULL AND
    PET_TYPE IS NOT NULL AND
    TEMPERAMENT IS NOT NULL AND
    COUNTRY IS NOT NULL AND
    DATE_BIRTH < GETDATE() AND
    GENDER IS NOT NULL AND
    HOBBY1 IS NOT NULL AND
    HOBBY2 IS NOT NULL AND
    HOBBY3 IS NOT NULL AND
    HOBBY4 IS NOT NULL AND
    COST IS NOT NULL;
GO

-- Create copy of primary key table
CREATE TABLE CopyPKPetData (
    petPK INT IDENTITY(1,1) PRIMARY KEY,
    PETNAME VARCHAR(250),
    PET_TYPE VARCHAR(250),
    TEMPERAMENT VARCHAR(250),
    COUNTRY VARCHAR(250),
    DATE_BIRTH DATE,
    GENDER VARCHAR(250),
    HOBBY1 VARCHAR(250),
    HOBBY2 VARCHAR(250),
    HOBBY3 VARCHAR(250),
    HOBBY4 VARCHAR(250),
    COST NUMERIC(8,2)
);
GO
INSERT INTO CopyPKPetData
    SELECT PETNAME, PET_TYPE, TEMPERAMENT, COUNTRY, DATE_BIRTH, GENDER, HOBBY1, HOBBY2, HOBBY3, HOBBY4, COST
    FROM PKPetData
    WHERE
    PETNAME IS NOT NULL AND
    PET_TYPE IS NOT NULL AND
    TEMPERAMENT IS NOT NULL AND
    COUNTRY IS NOT NULL AND
    DATE_BIRTH < GETDATE() AND
    GENDER IS NOT NULL AND
    HOBBY1 IS NOT NULL AND
    HOBBY2 IS NOT NULL AND
    HOBBY3 IS NOT NULL AND
    HOBBY4 IS NOT NULL AND
    COST IS NOT NULL;
GO

-- Populate look-up tables
INSERT INTO tblPET_TYPE (PetTypeName)
    SELECT DISTINCT PET_TYPE FROM PKPetData;
GO

INSERT INTO tblGENDER (GenderName)
    SELECT DISTINCT GENDER FROM PKPetData;
GO

INSERT INTO tblTEMPERAMENT (TempName)
    SELECT DISTINCT TEMPERAMENT FROM PKPetData;
GO

CREATE TABLE AllHobbies (
    HobbyName VARCHAR(250)
);
GO
INSERT INTO AllHobbies (HobbyName)
    SELECT DISTINCT HOBBY1 FROM PKPetData;
GO
INSERT INTO AllHobbies (HobbyName)
    SELECT DISTINCT HOBBY2 FROM PKPetData;
GO
INSERT INTO AllHobbies (HobbyName)
    SELECT DISTINCT HOBBY3 FROM PKPetData;
GO
INSERT INTO AllHobbies (HobbyName)
    SELECT DISTINCT HOBBY4 FROM PKPetData;
GO

INSERT INTO tblHOBBY (HobbyName)
    SELECT DISTINCT HobbyName FROM AllHobbies;
GO

INSERT INTO tblCOUNTRY (CountryName)
    SELECT DISTINCT COUNTRY FROM PKPetData;
GO